### ISSUE TITLE
Feature request: get rid of the annoying autocomplete boop

### ISSUE THREAD

**Issue by fraserw** [canfar/arcades#47]
The sound is grating at best, infuriating at worst. Can it be silenced? As far as I know there is no way to have a certain URL auto muted in common browsers...

**Comment by fraserw** [comment]
And to be clear, I already know how to mute tabs. Just wish I wouldn't have to.

**Comment by sfabbro** [comment]
I think this needs to go on this GitHub [link](https://github.com/opencadc/science-platform/issues) instead as this canfar/arcade which should probably be archived.

**Comment by fraserw** [comment]
Moving as suggested.
